// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class ImgLeftViewCell : UITableViewCell
	{
		public ImgLeftViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
