// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class ImgRightViewCell : UITableViewCell
	{
		public ImgRightViewCell (IntPtr handle) : base (handle)
		{
		}
	}
}
