// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class InfoWebViewController : UIViewController
	{
		public Product product { get; set;}

		public InfoWebViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			infoWebView.LoadRequest(new NSUrlRequest(new NSUrl(product.URL)));
		}
	}
}
