// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class OrderViewController : UIViewController
	{
		public Product product { get; set;}

		public OrderViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			lblName.Text = product.Name;
			lblPrice.Text = product.Price;
			imgProduct.Image = UIImage.FromFile(product.Img);
		}
	}
}
