// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Linq;
using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class OrderViewController : UIViewController
	{
		public Product product { get; set;}

		private MyDatePicker dPicker;
		private PickerToolbarView dateToolbar;

		private UIPickerView amountPicker;
		private AmountPickerModel amountModel;
		private PickerToolbarView amountToolbar;

		UIPickerView addrPicker;
		//AddressPickerModel addrModel;
		MyPickerModel addrModel;
		PickerToolbarView addrToolbar;

		#region AmountPicker Data
		private List<string> _items = Enumerable.Range(1, 100).Select(n => n.ToString()).ToList();
		#endregion

		#region Address Picker Data
		List<string> cityList = new List<string>()
			{
				"臺北市",
				"新北市",
				"桃園市",
				"臺中市",
				"臺南市",
				"高雄市"
			};

		List<List<string>> areaList = new List<List<string>>
			{
				new List<string>{
					"中正區",
					"大同區",
					"中山區",
					"松山區",
					"大安區",
					"萬華區",
					"信義區",
					"士林區",
					"北投區",
					"內湖區",
					"南港區",
					"文山區"
				},
				new List<string>{
					"板橋區",
					"新莊區",
					"中和區",
					"永和區",
					"土城區",
					"樹林區",
					"三峽區",
					"鶯歌區",
					"三重區",
					"蘆洲區",
					"五股區",
					"泰山區"
				},
				new List<string>{
					"桃園區",
					"中壢區",
					"平鎮區",
					"八德區",
					"楊梅區"
				},
				new List<string>{
					"北屯區",
					"西屯區",
					"南屯區",
					"太平區",
					"大里區",
					"霧峰區"
				},
				new List<string>{
					"麻豆區",
					"佳里區",
					"西港區",
					"七股區",
					"將軍區",
					"學甲區"
				},
				new List<string>{
					"左營區",
					"鼓山區",
					"三民區",
					"鹽埕區",
					"前金區",
					"新興區"
				}
			};
		#endregion

		public OrderViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			lblName.Text = product.Name;
			lblPrice.Text = product.Price;
			imgProduct.Image = UIImage.FromFile(product.Img);

			#region Date Picker
			dPicker = new MyDatePicker();
			dPicker.BackgroundColor = UIColor.White;
			dPicker.Mode = UIDatePickerMode.Date;

			dateToolbar = PickerToolbarView.Create();

			txtDate.InputView = dPicker;
			txtDate.InputAccessoryView = dateToolbar;
			dateToolbar.DoneEvent += _dateDone;
			dateToolbar.CancelEvent += _dateCancel;
			#endregion

			#region Amount Picker
			amountModel = new AmountPickerModel(_items);

			amountPicker = new UIPickerView();
			amountPicker.BackgroundColor = UIColor.White;
			amountPicker.Model = amountModel;

			amountToolbar = PickerToolbarView.Create();

			txtAmount.InputView = amountPicker;
			txtAmount.InputAccessoryView = amountToolbar;
			amountToolbar.DoneEvent += _numDone;
			amountToolbar.CancelEvent += _numCancel;
			#endregion

			#region Address Picker
			//addrModel = new AddressPickerModel(cityList, areaList);
			addrModel = new MyPickerModel(4);

			addrPicker = new UIPickerView();
			addrPicker.BackgroundColor = UIColor.White;
			addrPicker.Model = addrModel;

			addrToolbar = PickerToolbarView.Create();

			txtAddress.InputView = addrPicker;
			txtAddress.InputAccessoryView = addrToolbar;
			addrToolbar.DoneEvent += _addrDone;
			addrToolbar.CancelEvent += _addrCancel;
			#endregion
		}

		#region Toolbar's Event
		void _numDone(object sender, EventArgs e)
		{
			txtAmount.Text = amountModel.selectItem(amountPicker);
			int totalPrice = 0;
			if (txtAmount.Text != "")
			{
				totalPrice = Int32.Parse(txtAmount.Text) * Int32.Parse(lblPrice.Text);
				lblTotalPrice.Text = "$ " + totalPrice.ToString();
			}
			txtAmount.ResignFirstResponder();
		}
		void _numCancel(object sender, EventArgs e)
		{
			txtAmount.ResignFirstResponder();
			for (int i = 0; i < amountModel.cancelSelectedRow.Count; i++)
			{
				amountPicker.Select(amountModel.cancelSelectedRow[i], i, false);
			}
		}

		void _addrDone(object sender, EventArgs e)
		{
			txtAddress.Text = "";
			// combine title list and set txtAddress.Text
			foreach (var title in addrModel.pickerSelectDone(addrPicker))
			{
				txtAddress.Text += title;
			}
			txtAddress.ResignFirstResponder();
		}
		void _addrCancel(object sender, EventArgs e)
		{
			txtAddress.ResignFirstResponder();
			addrModel.pickerSelectCancel(addrPicker);
		}

		void _dateDone(object sender, EventArgs e)
		{
			DateTime dateTime = DateTime.SpecifyKind((DateTime)dPicker.Date, DateTimeKind.Unspecified);
			txtDate.Text = dateTime.ToString("MM-dd-yyyy");
			dPicker.initDate = dPicker.Date;
			txtDate.ResignFirstResponder();
		}
		void _dateCancel(object sender, EventArgs e)
		{
			txtDate.ResignFirstResponder();
			dPicker.SetDate(dPicker.initDate, false);
		}
		#endregion
	}
}
