// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace AppleTableView.iOS
{
	public partial class ProductListViewController : UIViewController
	{
		private List<List<Product>> products;
		private Product selectedProduct;

		public ProductListViewController (IntPtr handle) : base (handle)
		{
			#region Product List
			List<Product> iPhoneGroup = new List<Product>()
			{
				new Product
				{
					Name = "iPhone 7",
					URL = "http://www.apple.com/tw/iphone-7/",
					Img = "iphone.jpg",
					Price = "28500"
				},
				new Product
				{
					Name = "iPhone 6s",
					URL = "http://www.apple.com/tw/shop/buy-iphone/iphone6s",
					Img = "iphone6.png",
					Price = "22500"
				},
				new Product
				{
					Name = "iPhone SE",
					URL = "http://www.apple.com/tw/iphone-se/",
					Img = "iphoneSE.jpg",
					Price = "16500"
				}
			};

			List<Product> MacGroup = new List<Product>()
			{
				new Product
				{
					Name = "iMac",
					URL = "http://www.apple.com/tw/imac/",
					Img = "Mac.png",
					Price = "56800"
				},
				new Product
				{
					Name = "MacBook",
					URL = "http://www.apple.com/tw/macbook/",
					Img = "macbook.jpg",
					Price = "32500"
				},
				new Product
				{
					Name = "MacBook Air",
					URL = "http://www.apple.com/tw/macbook-air/",
					Img = "macbookAir.png",
					Price = "37500"
				},
				new Product
				{
					Name = "MacBook Pro",
					URL = "http://www.apple.com/tw/macbook-pro/",
					Img = "macbookPro.jpeg",
					Price = "47500"
				},

			};

			List<Product> iPadGroupt = new List<Product>()
			{
				new Product
				{
					Name = "iPad Pro",
					URL = "http://www.apple.com/tw/ipad-pro/",
					Img = "ipad.jpg",
					Price = "29500"
				},
				new Product
				{
					Name = "iPad Air",
					URL = "http://www.apple.com/tw/ipad-air-2/",
					Img = "ipadAir.jpg",
					Price = "21500"
				},
				new Product
				{
					Name = "iPad mini",
					URL = "http://www.apple.com/tw/ipad-mini-4/",
					Img = "ipadMini.jpg",
					Price = "16500"
				}

			};

			List<Product> iWatchGroup = new List<Product>()
			{
				new Product
				{
					Name = "iWatch",
					URL = "http://www.apple.com/tw/watch/",
					Img = "iWatch.jpg",
					Price = "8500"
				}
			};
			#endregion

			products = new List<List<Product>>
			{
				iPhoneGroup,
				MacGroup,
				iPadGroupt,
				iWatchGroup
			};
		}

		public override void ViewDidLoad()
		{
			base.ViewDidLoad();

			var tbSource = new TableSource(products);
			// 設定內容
			productTableView.Source = tbSource;
			// 委派事件
			tbSource.SelectTableInfo += _selectInTableInfo;
			tbSource.SelectTableBuy += _selectInTableBuy;
		}

		#region GoToNextView
		void _selectInTableInfo(object sender, NSIndexPath e)
		{
			selectedProduct = products[e.Section][e.Row];
			PerformSegue("GoToInfoWebView", this);
		}
		void _selectInTableBuy(object sender, NSIndexPath e)
		{
			selectedProduct = products[e.Section][e.Row];
			PerformSegue("GoToOrderView", this);
		}

		public override void PrepareForSegue(UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue(segue, sender);

			if (segue.Identifier.Equals("GoToInfoWebView"))
			{
				var dvc = segue.DestinationViewController as InfoWebViewController;
				dvc.product = selectedProduct;
			}

			if (segue.Identifier.Equals("GoToOrderView"))
			{
				var dvc = segue.DestinationViewController as OrderViewController;
				dvc.product = selectedProduct;
			}
		}
		#endregion
	}
}
